[project]
name = "reddit-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.7",
    "uvicorn>=0.35.0",
]
